# -*- coding: utf-8 -*-
"""daily_vaccinations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XitnZ8rctjeKhk1_3SRt-19BPp2Qvb9S

Code Implementation Task: Implement code to fill the missing dat(impute) in daily_vaccinations column per country with the minimum daily vaccination number of relevant countries.  
Note: If a country does not have any valid vaccination number yet, fill it with “0” (zero).
"""

import pandas as pd
import numpy as np

df = pd.read_excel('country_vaccination_stats.xlsx')

def fill_missing_vaccinations(df):
    min_vaccinations = df.groupby('country')['daily_vaccinations'].transform(lambda x: x[x > 0].min())

    df['daily_vaccinations'] = df.apply(
        lambda row: min_vaccinations[row.name] if pd.isna(row['daily_vaccinations']) else row['daily_vaccinations'], axis=1
    )
    df['daily_vaccinations'] = df['daily_vaccinations'].fillna(0)

    return df

df = fill_missing_vaccinations(df)

df.to_excel('country_vaccination_stats_updated.xlsx', index=False)

print(df)