# -*- coding: utf-8 -*-
"""daily_vaccinations_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gD-M9cLKfUaABbHRIEnhWCZ4rPWf7rSz
"""

import pandas as pd

df = pd.read_excel('country_vaccination_stats.xlsx')

def fill_missing_vaccinations(df):
    min_vaccinations = df.groupby('country')['daily_vaccinations'].transform(lambda x: x[x > 0].min())

    df['daily_vaccinations'] = df.apply(
        lambda row: min_vaccinations[row.name] if pd.isna(row['daily_vaccinations']) else row['daily_vaccinations'], axis=1
    )
    df['daily_vaccinations'] = df['daily_vaccinations'].fillna(0)

    return df

df = fill_missing_vaccinations(df)
df.to_excel('country_vaccination_stats_updated.xlsx', index=False)

mean_daily_vaccinations = df.groupby('country')['daily_vaccinations'].mean().sort_values(ascending=False)

top_3_countries = mean_daily_vaccinations.head(3)

print("Top 3 countries with highest mean daily vaccination numbers:")
print(top_3_countries)